package sstable

const (
	INDEX_KEY_SIZE   = 32
	INDEX_ENTRY_SIZE = INDEX_KEY_SIZE + 8
)
const (
	SUMMARY_KEY_SIZE    = INDEX_KEY_SIZE
	SUMMARY_ENTRY_SIZE  = SUMMARY_KEY_SIZE + 8
	SUMMARY_HEADER_SIZE = SUMMARY_KEY_SIZE * 2
	SUMMARY_STEP        = 4
)
